import 'package:cached_network_image/cached_network_image.dart';
import '../../../../core/constants/app_string.dart';
import '/core/router/router_imports.dart';
import '/features/home/presentation/controllers/home_controller.dart';
import 'package:flutter/Material.dart';
import 'package:flutter_screenutil/flutter_screenutil.dart';
import 'package:flutter_svg/svg.dart';
import 'package:get/get.dart';
import 'package:velocity_x/velocity_x.dart';
import '../../../../core/constants/app_assets.dart';
import '/core/constants/app_color.dart';

import '/shared/widgets/widget_imports.dart';
import 'package:flutter/material.dart';
import '../../domain/model/product_model.dart';
part 'product_tile.dart';
part 'filter_card.dart';
part 'filter_item_widget.dart';
part 'checkbox_tile.dart';
